steps:
- name: 'gcr.io/cloud-builders/npm'
  env:
    - 'DB_NAME=${_DB_NAME}'
    - 'DB_PASS=${_DB_PASS}'
    - 'DB_PORT=${_DB_PORT}'
    - 'DB_USER=${_DB_USER}'
    - 'INSTANCE_UNIX_SOCKET=${_INSTANCE_UNIX_SOCKET}'
  entrypoint: 'npm'
  args: ['run', 'start']