steps:
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['install']
- id: proxy-install
  name: gcr.io/cloud-builders/npm
  entrypoint: sh
  args:
    - "-c"
    - "wget https://storage.googleapis.com/cloudsql-proxy/v1.20.1/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy"
- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'DATABASE_URL=${_DATABASE_URL}'
  entrypoint: 'npx'
  args: ['(./cloud_sql_proxy -dir=/cloudsql -instances=<CLOUD_SQL_CONNECTION> & sleep 2) && prisma migrate deploy']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-client']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-server']
- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'DB_NAME=${_DB_NAME}'
  - 'DB_PASS=${_DB_PASS}'
  - 'DB_PORT=${_DB_PORT}'
  - 'DB_USER=${_DB_USER}'
  - 'DB_HOST=${_DB_HOST}'
  args: ['(./cloud_sql_proxy -dir=/cloudsql -instances=<CLOUD_SQL_CONNECTION> & sleep 2) && npm run start']