steps:
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-client']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-server']