steps:
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['install']
- id: proxy-install
  name: gcr.io/cloud-builders/npm
  entrypoint: sh
  args:
    - "-c"
    - "wget https://storage.googleapis.com/cloudsql-proxy/v1.20.1/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy"
# - name: 'gcr.io/cloud-builders/npm'
#   env:
#   - 'DATABASE_URL=${_DATABASE_URL}'
#   entrypoint: 'sh'
#   args: ['-c', '(./cloud_sql_proxy -dir=/cloudsql -instances=hackjobgameswebsite:us-east1:hackjobgamesdatabase & sleep 2) && npx prisma migrate deploy']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-client']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-server']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hackjobwebsite:$COMMIT_SHA', '.' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hackjobwebsite'
  - '--image'
  - 'gcr.io/$PROJECT_ID/hackjobwebsite:$COMMIT_SHA'
  - '--region'
  - 'us-east1-b'
images:
- 'gcr.io/$PROJECT_ID/hackjobwebsite:$COMMIT_SHA'