steps:
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['install']
- id: proxy-install
  name: gcr.io/cloud-builders/npm
  entrypoint: sh
  args:
    - "-c"
    - "wget https://storage.googleapis.com/cloudsql-proxy/v1.20.1/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy"
# - name: 'gcr.io/cloud-builders/npm'
#   env:
#   - 'DATABASE_URL=${_DATABASE_URL}'
#   entrypoint: 'sh'
#   args: ['-c', '(./cloud_sql_proxy -dir=/cloudsql -instances=hackjobgameswebsite:us-east1:hackjobgamesdatabase & sleep 2) && npx prisma migrate deploy']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-client']
- name: 'gcr.io/cloud-builders/npm'
  env:
  entrypoint: 'npm'
  args: ['run', 'build-server']

- name: 'gcr.io/cloud-builders/gcloud'
  env:
  - 'DB_NAME=${_DB_NAME}'
  - 'DB_PASS=${_DB_PASS}'
  - 'DB_PORT=${_DB_PORT}'
  - 'DB_USER=${_DB_USER}'
  - 'DB_HOST=${_DB_HOST}'
  entrypoint: 'sh'
  args: ['-c', '(./cloud_sql_proxy -dir=/cloudsql -instances=hackjobgameswebsite:us-east1:hackjobgamesdatabase & sleep 2) && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash && [ -s "/builder/home/.nvm/nvm.sh" ] && \. "/builder/home/.nvm/nvm.sh"  && nvm install 18 && npm run start']

# - name: 'gcr.io/cloud-builders/gcloud'
#   env:
#   - 'DB_NAME=${_DB_NAME}'
#   - 'DB_PASS=${_DB_PASS}'
#   - 'DB_PORT=${_DB_PORT}'
#   - 'DB_USER=${_DB_USER}'
#   - 'DB_HOST=${_DB_HOST}'
#   entrypoint: 'sh'
#   args: ['-c','curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash && [ -s "/builder/home/.nvm/nvm.sh" ] && \. "/builder/home/.nvm/nvm.sh"  && nvm install 18 && npm run hello']